### ISSUE TITLE
text is not translated :(

### ISSUE THREAD

**Issue by fatalpowa** [IllusionMods/RG-Translation#10]
Hello,

I have install all the prerequisites and follow all the installation steps but I don't see any text translated, only the main menu (new game, load game, etc..) and some textures but nothing else.

What am I doing wrong?

Thanks in advance,
FP

**Comment by ManlyMarco** [comment]
It could be literally anything, try asking in help channel on the discord server or try using the RG HF Patch to make sure everything is actually installed properly.
