### ISSUE TITLE
How to translate Texture/Image for RG?

### ISSUE THREAD

**Issue by flywhc** [IllusionMods/RG-Translation#5]
I tried to edit AutoTranslatorConfig.ini and enable texture translation and dump:
````
[Texture]
TextureDirectory=Translation\{Lang}\Texture
EnableTextureTranslation=True
EnableTextureDumping=True
EnableTextureToggling=False
EnableTextureScanOnSceneLoad=True
````
After running RG, I cannot find images like your dumped file sp_rg_help_00_00 [1E94572625-1B4D71021D].png in my Texture folder but some other files doesn't contain any text to be translated.

I also tried to modify images files from [RG-Translation](https://github.com/IllusionMods/RG-Translation)/[Image Source Files](https://github.com/IllusionMods/RG-Translation/tree/main/Image%20Source%20Files)/OriginalFiles/ and copy them into my Texture folder. However the game didn't show my modification.

I am using:
[[ScrewThisNoise][Illusion] RoomGirl (ROOMガール) BetterRepack R1.3](https://sukebei.nyaa.si/view/3753382)
BepInEx.IL2CPP.dll 6.0.0 pre-1
XUnity.AutoTranslator.Plugin.BepInEx-IL2CPP.dll 5.1.0
XUnity.AutoTranslator.Plugin.Core.dll 5.1.0

**Comment by SpockBauru** [comment]
Please coordinate with other translators in Discord server to avoid two people working in the same thing causing waste of effort, which is specially bad for a game with few modders like RG: https://discord.gg/illusionsoft -> go to `translation` channel.

For your issue, take a look in the config file from this repository in `config` folder. BetterRepack 1.3 is using an older version of `AutoTranslatorConfig.ini` that is a way different from the current version which include texture translation.

**Comment by flywhc** [comment]
Thank you. It works.
I am trying to translate images into Chinese. It seems nobody has worked on it.
It is my first time using Discord so I couldn't find the Translation channel.
I think it is fine because I was the only one did HS2 image translation into Chinese.
